drop table if exists task_domain CASCADE;
drop table if exists to_do_domain CASCADE;
create table mission_domain (id bigint generated by default as identity, responsibility varchar(255), completedstatus boolean, nameofmission varchar(255), orderofimportance integer, my_to_do_id bigint, primary key (id));
create table to_do_domain (id bigint generated by default as identity, list_name varchar(255), primary key (id));